
services:
  api:
    build: ./api
    image: dm-api:v1
    environment:
      - PORT=5000
    ports:
      - "5001:5000"

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=dernier_metro
    ports:
      - "5433:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data

  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
      - BASE_URL=/
      - SWAGGER_JSON_URL=http://localhost:8080/openapi/openapi.yaml
    volumes:
      - ./openapi:/usr/share/nginx/html/openapi:ro
    ports:
      - "8080:8080"
    depends_on:
      - api
      - postgres

volumes:
  pgdata:
